### ISSUE TITLE
could not determine type "FTNOTE"

### ISSUE THREAD

**Issue by franke-biosaxs** [AUSAXS/AUSAXS#104]
```
% bin/saxs_fitter 6lyz.pdb lyzexp.dat 
Running AUSAXS v1.0.3
Reading PDB file from "./6lyz.pdb"
Record::get_type: Could not determine type "FTNOTE"
libc++abi: terminating due to uncaught exception of type std::exception: std::exception
zsh: abort      bin/saxs_fitter 6lyz.pdb lyzexp.dat
```
The two files are both in the crysol example in your ATSAS installation (which I assume you have). I can attach them otherwise.

This particular test case is a bit unfair as the 6lyz.pdb is positively ancient and does not follow current PDB standards. I intentionally keep it around for exactly these kind of tests.

**Comment by klytje** [comment]
Upon closer examination of the file in question, I've decided _not_ to support these older files. Primarily because newer versions of the files, compliant with the latest PDB specification, are readily available (see e.g. your example [6lyz](https://www.rcsb.org/versions/6LYZ) file, which has received several compliance updates since the 1987 version present in ATSAS).

This is primarily because I realized supporting these older files would require significant changes to the current PDB parser, as the older ATOM records diverge significantly from the modern ones.
